# Generated by Django 3.1.3 on 2020-11-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20201112_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.customuser', verbose_name='Покупатель'),
            preserve_default=False,
        ),
    ]
